name:                glenside-hs
version:             0.1.0.0
github:              "githubuser/glenside-hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/glenside-hs#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.5.1
- Stack >= 0.4.0

library:
  source-dirs: src

executables:
  glenside-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glenside-hs
    when:
    - condition: false
      other-modules: Paths_glenside_hs  # your package name here


tests:
  glenside-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glenside-hs
